const MOVE_FORWARD = "MOVE_FORWARD";
const MOVE_RIGHT = "MOVE_RIGHT";
const MOVE_LEFT = "MOVE_LEFT";

const START_ANIMATION = "START_ANIMATION";
const SET_ORDERS = "SET_ORDERS";
const RESET_ORDERS_OR_NEXT_ROVER = "RESET_ORDERS_OR_NEXT_ROVER";

const LOAD_MOVEMENTS = "LOAD_MOVEMENTS";
const RUN_ROVER = "RUN_ROVER";
const UPDATE_GRID = "UPDATE_GRID";

const SET_MESSAGE = "SET_MESSAGE";
const RESET_MESSAGE = "RESET_MESSAGE";

const RESET = "RESET";

export default {
	MOVE_FORWARD,
	MOVE_RIGHT,
	MOVE_LEFT,
	LOAD_MOVEMENTS,
	RUN_ROVER,
	UPDATE_GRID,
	SET_MESSAGE,
	RESET_MESSAGE,
	START_ANIMATION,
	SET_ORDERS,
	RESET_ORDERS_OR_NEXT_ROVER,
	RESET,
};
